Add nixpkgs-fmt to shell and CI
input-output-hk/ouroboros-network pull request #3005
Opened 2021-03-19 12:46 UTC by EncodePanda

Fixes #2980 

One less thing to worry about.

Btw it integrates nicely with Emacs.

```
(use-package nixpkgs-fmt)
;; format all nix files on save
(add-hook 'nix-mode-hook 'nixpkgs-fmt-on-save-mode)
```

2021-03-19 15:27 UTC, nfrisby commented
LGTM but I'll let @coot Approve -- he touches Nix more than I do 👍

2021-03-22 09:15 UTC, nc6 approved these changes
LGTM. Maybe you want to add a note to the style guide somewhere talking about the nix formatter

2021-03-22 10:01 UTC, coot commented
I think @jbgi should review this PR. @jbgi is there a recommended formatter for `nix`?

2021-03-22 10:51 UTC, jbgi requested changes
Small changed needed.
There is an alternative approach used in plutus that may be interesting, which integrate with hydra and provide a pre-commit hook via https://github.com/cachix/pre-commit-hooks.nix, cf.:
https://github.com/input-output-hk/plutus/blob/master/nix/tests/nixpkgs-fmt.nix
https://github.com/input-output-hk/plutus/blob/86ee2701586c26d0c85961533f5c82f1ee3ff076/shell.nix#L32-L38
cc/ @disassembler

2021-03-22 10:51 UTC, jbgi commented on scripts/buildkite/check-nixpkgs-fmt.sh
> +nixpkgs-fmt `git ls-files -- '*.nix'`
```suggestion
nixpkgs-fmt `git ls-files -- '*.nix' ':!:nix/sources.nix'`
```
```nix/sources.nix``` is generated by `niv` which will print a warning if the files has changed (thinking it is not up-to-date).

2021-03-22 14:08 UTC, jbgi approved these changes

2021-03-22 14:52 UTC, EncodePanda commented
bors merge

2021-03-22 15:23 UTC, merged