Add Win32-network hash
input-output-hk/ouroboros-network pull request #3022
Opened 2021-03-28 23:59 UTC by newhoggy

2021-03-29 22:50 UTC, nfrisby commented
FYI, I changed the reviewers to just @coot.

2021-03-30 06:34 UTC, coot requested changes

2021-03-30 06:34 UTC, coot commented on cabal.project
> +  --sha256: 1ggm3239z41z0ca9al43v9y2wmf20bbmdgj1k27kyph54gqkdbhn
Use: `94153b676617f8f33abe8d8182c37377d2784bd1` tag, `f71be` is not on `master` anymore.

2021-03-30 06:48 UTC, newhoggy commented
Updated to:

```
source-repository-package
  type: git
  location: https://github.com/input-output-hk/Win32-network
  tag: 94153b676617f8f33abe8d8182c37377d2784bd1
  --sha256: 0pb7bg0936fldaa5r08nqbxvi2g8pcy4w3c7kdcg7pdgmimr30ss
```

2021-03-30 06:48 UTC, coot reviewed
LGTM

2021-03-30 10:57 UTC, coot approved these changes
LGTM

2021-03-30 10:58 UTC, coot commented
bors merge

2021-03-30 13:54 UTC, merged