Update information about nix configuration
input-output-hk/ouroboros-network pull request #3048
Opened 2021-04-08 10:43 UTC by EncodePanda

2021-04-08 23:30 UTC, nfrisby requested changes
Nice simplification! One last hiccup: the section title is stale now.

2021-04-08 23:30 UTC, nfrisby commented on ouroboros-consensus/docs/Onboarding.md
>  ##### 2. cachix
Rename this to "caching" or maybe "substituters"?

2021-04-12 11:48 UTC, Jasagredo approved these changes
Apart from @nfrisby comment, looks good to me.

2021-04-14 07:22 UTC, EncodePanda commented
bors merge

2021-04-14 07:24 UTC, EncodePanda commented
@nfrisby this is ready for review now

2021-04-14 13:06 UTC, nfrisby approved these changes
Nice 👍 

Approved

2021-04-14 13:13 UTC, EncodePanda commented
bors merge

2021-04-14 14:08 UTC, merged