Add support for V7 keepalive
input-output-hk/ouroboros-network pull request #3193
Opened 2021-05-28 08:18 UTC by karknu

NodeToNode version 7 fixed the cbor encoding for the keepalive
miniprotocol.

2021-05-28 08:18 UTC, karknu commented
Fixes #3187.

2021-05-31 08:29 UTC, jbgi commented
tested successfully on alonzo-blue.

2021-06-02 07:22 UTC, coot requested changes

2021-06-02 07:22 UTC, coot commented on network-mux/demo/cardano-ping.hs
> +    keepAlive bearer timeoutfn peerStr version td cookie = do
```suggestion
    keepAlive bearer timeoutfn peerStr version td !cookie = do
```

2021-06-02 09:22 UTC, karknu commented
bors r+

2021-06-02 09:39 UTC, merged