Sync progress partial config
input-output-hk/ouroboros-network pull request #3202
Opened 2021-06-07 13:24 UTC by newhoggy

2021-06-08 15:07 UTC, coot requested changes

2021-06-08 15:07 UTC, coot commented on ouroboros-network/src/Ouroboros/Network/NodeToClient/Version.hs
> +  , nodeToClientVersionCodec
I don't think this change is necessary.

2021-06-08 19:43 UTC, nfrisby requested changes
I looked at the last three commits. The first two were non-functional changes and the third seems confused.

@newhoggy Does the `cardano-node` progress bar need something more than `GetPartialLedgerConfig`? I suspect that's what @DavidEichmann is working towards right now. I didn't see anything within the commits in this PR that you solo authored that seemed to go beyond what I think David is currently doing.

If there is, would you reorganize the commits a bit so that it's more obvious what content you're proposing is this PR?

Also, if the PR is not ready for merge, please put it in the Draft PR state. Thanks!

2021-06-08 19:43 UTC, nfrisby commented on ouroboros-consensus/src/Ouroboros/Consensus/Ledger/Query.hs
> +      TopLevelQueryDisabled ->
When `ToplevelQueryDisabled`, there are no top-level queries. That's why the previous code was correct and the new code here is contradictory.

Before we have any activated top-level queries, we'll have to introduce a `TopLevelQueryV_1` or some such in that enumeration type.

2021-06-09 10:35 UTC, karknu commented
Could this PR get a description?
 From a network perspective it doesn't seem to have much to do with "sync progress partial config".

2021-11-05 10:03 UTC, closed without merging