Match all components in nix check stylish scripts
input-output-hk/ouroboros-network pull request #3719
Opened 2022-04-21 07:12 UTC by coot

This fixes a mistake in #3698 which removed a `*` pattern but did not provide
a way to check all the other components.

2022-04-21 07:29 UTC, dnadales approved these changes

2022-04-21 07:39 UTC, coot commented
I still have a problem with this nix script.  When I run:
```
fd -p ouroboros-network-framework -e hs -E Setup.hs -X stylish-haskell -c .stylish-haskell-network.yaml
```
Then I get a massive diff, but `nix-build -A checks.styles.check-stylish-network` succeeds.

2022-04-21 10:14 UTC, amesgen requested changes
> I still have a problem with this nix script. When I run:
> 
> ```
> fd -p ouroboros-network-framework -e hs -E Setup.hs -X stylish-haskell -c .stylish-haskell-network.yaml
> ```
> 
> Then I get a massive diff, but `nix-build -A checks.styles.check-stylish-network` succeeds.

I think the problem here is that `echo $? > $out` is not actually checking anything, as `stylish-haskell -i` will succeed with exit code 0 even if it reformatted files. To fix this, we could use `git diff --exit-code` instead (but `git` has to be added to the derivation for this).

2022-04-21 10:19 UTC, coot commented
@amesgen afaik that's indeed the problem, I reported this on [slack](https://input-output-rnd.slack.com/archives/CDA6LUXAQ/p1650527906313109?thread_ts=1648694931.837859&cid=CDA6LUXAQ).

2022-04-21 10:21 UTC, coot commented on nix/check-stylish.nix
> +  fd -p ouroboros-consensus-test -e hs -E Setup.hs -X stylish-haskell -c .stylish-haskell.yaml -i
You're right, it already matches all the files.

2022-04-21 10:22 UTC, coot commented on nix/check-stylish.nix
> +  fd -p ouroboros-consensus-test -e hs -E Setup.hs -X stylish-haskell -c .stylish-haskell.yaml -i
Fixed.

2022-04-21 10:26 UTC, coot commented
I changed the title and description to match the current state of the patch.  We still need make sure the script fails when it returns.

2022-04-22 17:44 UTC, amesgen approved these changes

2022-05-16 16:42 UTC, amesgen commented
Mostly superseded by #3722

2022-05-16 16:42 UTC, closed without merging