Minor typos in code comments.
input-output-hk/ouroboros-network pull request #3776
Opened 2022-05-28 01:29 UTC by tmcgilchrist

2022-05-30 07:08 UTC, coot requested changes

2022-06-02 01:30 UTC, tmcgilchrist commented on ouroboros-network-framework/src/Ouroboros/Network/Snocket.hs
> +  , socketFileDescriptor
Reverted too.

2022-06-04 11:17 UTC, coot approved these changes
LGTM

2022-06-04 11:17 UTC, coot commented
bors merge

2022-06-13 05:21 UTC, coot commented
bors merge

2022-06-13 06:58 UTC, merged