Forward also through current mempool diffs
input-output-hk/ouroboros-network pull request #3994
Opened 2022-09-07 15:04 UTC by Jasagredo

# Description

Also forwards the differences through the changes already in the mempool. Solves what is described in #3993 

Part of #3993.

# Checklist

- Branch
    - [X] Commit sequence broadly makes sense
    - [X] Commits have useful messages
    - [ ] New tests are added if needed and existing tests are updated
    - [X] If this branch changes Consensus and has any consequences for downstream repositories or end users, said changes must be documented in [`interface-CHANGELOG.md`](../ouroboros-consensus/docs/interface-CHANGELOG.md)
    - [X] If this branch changes Network and has any consequences for downstream repositories or end users, said changes must be documented in [`interface-CHANGELOG.md`](../docs/interface-CHANGELOG.md)
    - [X] If serialization changes, user-facing consequences (e.g. replay from genesis) are confirmed to be intentional.
- Pull Request
    - [X] Self-reviewed the diff
    - [X] Useful pull request description at least containing the following information:
      - What does this PR change?
      - Why these changes were needed?
      - How does this affect downstream repositories and/or end-users?
      - Which ticket does this PR close (if any)? If it does, is it [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?
    - [X] Reviewer requested

2022-09-08 13:47 UTC, jorisdral requested changes
LGTM overall, though I did request a few minor changes

2022-09-08 13:47 UTC, jorisdral commented on ouroboros-consensus/src/Ouroboros/Consensus/Mempool/Impl.hs
> +                                            , LedgerTables (ExtLedgerState blk) KeysMK)
```suggestion
                                            , LedgerTables (ExtLedgerState blk) KeysMK
                                            )
```

2022-09-08 13:47 UTC, jorisdral commented on ouroboros-consensus/src/Ouroboros/Consensus/Mempool/Impl.hs
> +        -> (ExtLedgerState blk EmptyMK -> m ( a
It might make sense to return a custom datatype instead of a triple

2022-09-08 13:47 UTC, jorisdral commented on ouroboros-consensus/src/Ouroboros/Consensus/Storage/LedgerDB/InMemory.hs
> +forwardTableKeySets dblog mempoolDiffs = \(UnforwardedReadSets seqNo' values keys) ->
The diffs are not necessarily mempool specific from the perspective of `forwardTableKeySets`, so maybe rename `mempoolDiffs` to something like `extraDiffs` or `auxDiffs`? Might also be good to document the parameter

2022-09-08 13:47 UTC, jorisdral commented on ouroboros-consensus/src/Ouroboros/Consensus/Storage/LedgerDB/InMemory.hs
> +               -> DiffMK    k v
```suggestion
    cumulative :: 
         Ord k
      => SeqDiffMK k v
      -> DiffMK    k v
```

2022-09-08 13:47 UTC, jorisdral commented on ouroboros-consensus/src/Ouroboros/Consensus/Storage/LedgerDB/InMemory.hs
> +            -> DiffMK    k v
```suggestion
    prepend :: 
         Ord k
      => SeqDiffMK k v
      -> DiffMK    k v
      -> DiffMK    k v
```

2022-09-08 13:47 UTC, jorisdral commented on ouroboros-consensus/src/Ouroboros/Consensus/Storage/LedgerDB/InMemory.hs
> +    prepend diffs1 diffs2 = rawPrependDiffs (cumulative diffs1) diffs2
I don't know if you agree, but ideally the types defined in the `HD` module should be opaque, such that we can't manipulate types like `UtxoDiff` in an unsafe way, but that is probably something for another PR (integration of anti-diffs perhaps?).

2022-09-15 08:37 UTC, Jasagredo commented
So this was in fact quite hidden, but it is already implemented, precisely in [this line](https://github.com/input-output-hk/ouroboros-network/blob/feature/utxo-hd/ouroboros-consensus/src/Ouroboros/Consensus/Mempool/Impl/Types.hs#L304). Only if we don't resync with the ledger, we have to use the same differences. Otherwise (as in the otherwise branch of those guards), we will apply all the transactions again so we must not forward through the mempool diffs.

2022-09-15 08:37 UTC, closed without merging