Happy new year :)
input-output-hk/ouroboros-network pull request #4249
Opened 2023-01-02 10:00 UTC by coot

2023-01-04 09:09 UTC, bolt12 approved these changes

2023-01-04 09:09 UTC, bolt12 commented on ouroboros-consensus-byron-test/NOTICE
> +Copyright 2019-2022 Input Output Global Inc (IOG)
Should this be 2023 as well?

2023-01-04 09:09 UTC, bolt12 commented on ouroboros-consensus/NOTICE
> +Copyright 2019-2022 Input Output Global Inc (IOG)
What about here?

2023-01-09 10:57 UTC, bolt12 requested changes

2023-01-09 10:57 UTC, bolt12 commented on ouroboros-consensus-byron-test/NOTICE
> +Copyright 2019-2022 Input Output Global Inc (IOG)
Was this changed in a different commit?

2023-01-09 16:40 UTC, coot commented on ouroboros-consensus-byron-test/NOTICE
> +Copyright 2019-2022 Input Output Global Inc (IOG)
it seems not, done now.

2023-01-09 16:40 UTC, coot commented on ouroboros-consensus/NOTICE
> +Copyright 2019-2022 Input Output Global Inc (IOG)
Fixed.

2023-01-09 17:10 UTC, bolt12 approved these changes

2023-01-09 17:11 UTC, amesgen approved these changes
Happy new year :tada:

2023-01-10 17:11 UTC, merged