Add ad hoc benchmark results
input-output-hk/ouroboros-network pull request #4295
Opened 2023-01-19 17:01 UTC by dnadales

This commit adds a new file which will contain the UTxO HD feature documentation. The document is bootstrapped with the latest ad-hoc benchmarks for replaying and syncing up to slot 75M. 

The outdated content from `docs/utxo-hd.md` was moved to `

# Checklist

- Branch
    - [ ] Commit sequence broadly makes sense
    - [ ] Commits have useful messages
    - [ ] The documentation has been properly updated
    - [ ] New tests are added if needed and existing tests are updated
    - [ ] If this branch changes Consensus and has any consequences for downstream repositories or end users, said changes must be documented in [`interface-CHANGELOG.md`](../ouroboros-consensus/docs/interface-CHANGELOG.md)
    - [ ] If this branch changes Network and has any consequences for downstream repositories or end users, said changes must be documented in [`interface-CHANGELOG.md`](../docs/interface-CHANGELOG.md)
    - [ ] If serialization changes, user-facing consequences (e.g. replay from genesis) are confirmed to be intentional.
- Pull Request
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description at least containing the following information:
      - What does this PR change?
      - Why these changes were needed?
      - How does this affect downstream repositories and/or end-users?
      - Which ticket does this PR close (if any)? If it does, is it [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?
    - [ ] Reviewer requested

2023-01-19 17:04 UTC, Jasagredo approved these changes

2023-01-20 07:39 UTC, jorisdral approved these changes

2023-01-20 13:32 UTC, Jasagredo requested changes

2023-01-20 13:32 UTC, Jasagredo commented on ouroboros-consensus/docs/utxo-hd.md
> +| UTxO HD (in-mem) | 13 GB          | 1:50 h      | 16 GB        | 25:04 h   |
I just realized this is wrong
```suggestion
| UTxO HD (in-mem) | 13 GB          | 2:50 h      | 16 GB        | 25:04 h   |
```

2023-01-23 15:15 UTC, Jasagredo approved these changes

2023-01-23 15:15 UTC, merged