Fixed cddl spec for tx-submission protocol
input-output-hk/ouroboros-network pull request #4580
Opened 2023-06-01 09:14 UTC by coot

We should use `tx` rather than `txId` in the cddl.  It only works
because we use `int` for both.

2023-06-01 09:42 UTC, bolt12 approved these changes

2023-06-13 07:52 UTC, coot commented
@bolt12 I changed this PR considerably, so please review it again.

We should use this idea in other mini-protocols / specs as well.  The only question is if we should modify data structure in `ouroboros-network-protocols:test` or provide different data structures just for `ouroboros-network-protocols:cddl`?

2023-06-13 08:59 UTC, bolt12 requested changes
Nice, is there an open issue about this? Would be nice to track this nice improvement

2023-06-13 13:44 UTC, coot commented on ouroboros-network-protocols/testlib/Ouroboros/Network/Protocol/TxSubmission2/Test.hs
> +        _             -> []
I was thinking rather to have `Any` newtype wrapper, but that's only useful if we do this kind of thing for other mini-protocols too.

2023-06-13 13:50 UTC, coot commented
I created the issue: input-output-hk/ouroboros-network#4595

2023-06-13 14:38 UTC, bolt12 commented on ouroboros-network-protocols/testlib/Ouroboros/Network/Protocol/TxSubmission2/Test.hs
> +        _             -> []
Yes that makes sense :)

2023-06-13 20:10 UTC, merged

2023-09-15 12:49 UTC, oskin1 commented on ouroboros-network-protocols/test-cddl/specs/common.cddl
> +tx           = any
Where can I find specification of what is expected here by the actual cardano-node implementation?

2023-09-15 12:50 UTC, oskin1 commented on ouroboros-network-protocols/test-cddl/specs/common.cddl
> +tx           = any
@coot